<?php
include '../includes/header.php';
require '../auth/connection.php';

if (!isset($_SESSION['user_id'])) {
    header("Location: ../auth/login.php");
    exit();
}

$user_id   = $_SESSION['user_id'];
$user_name = $_SESSION['user_name'] ?? 'User';

/* ---------- STAT FUNCTION ---------- */
// Helper function to fetch specific counts
function getStat($conn, $sql, $user_id) {
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("i", $user_id);
    $stmt->execute();
    $result = $stmt->get_result();
    $count = $result->fetch_assoc()['total'];
    $stmt->close();
    return $count;
}

/* ---------- DASHBOARD STATS (ALL STATUSES) ---------- */
// 1. Total
$totalOrders = getStat($conn, "SELECT COUNT(*) AS total FROM neworders WHERE user_id = ?", $user_id);

// 2. Pending
$pending = getStat($conn, "SELECT COUNT(*) AS total FROM neworders WHERE user_id = ? AND status='Pending'", $user_id);

// 3. Picked Up
$pickedUp = getStat($conn, "SELECT COUNT(*) AS total FROM neworders WHERE user_id = ? AND status='Picked Up'", $user_id);

// 4. In Transit
$inTransit = getStat($conn, "SELECT COUNT(*) AS total FROM neworders WHERE user_id = ? AND status='In Transit'", $user_id);

// 5. Out for Delivery
$outDelivery = getStat($conn, "SELECT COUNT(*) AS total FROM neworders WHERE user_id = ? AND status='Out for Delivery'", $user_id);

// 6. Delivered
$delivered = getStat($conn, "SELECT COUNT(*) AS total FROM neworders WHERE user_id = ? AND status='Delivered'", $user_id);

/* ---------- RECENT ORDERS ---------- */
$recentOrdersSql = "
    SELECT 
        id, sender_name, sender_phone, sender_email,
        receiver_name, receiver_phone, receiver_email,
        status, tracking_id, created_at
    FROM neworders
    WHERE user_id = ?
    ORDER BY id DESC LIMIT 5";

$stmt = $conn->prepare($recentOrdersSql);
$stmt->bind_param("i", $user_id);
$stmt->execute();
$recentOrders = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt->close();
?>

<style>
/* Dashboard Grid Layout */
.dashboard {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 1.5rem;
  padding: 2rem 5%;
}

.card {
  background: #fff;
  padding: 1.5rem;
  border-radius: 12px;
  box-shadow: 0 4px 12px rgba(0,0,0,0.08);
  text-align: center;
  transition: transform 0.3s ease;
  border-bottom: 4px solid transparent; /* Colored border bottom */
}

.card:hover { transform: translateY(-5px); }
.card h2 { font-size: 2rem; margin: 0; color: #333; }
.card p { margin-top: 5px; color: #666; font-size: 0.9rem; font-weight: 500; }

/* Specific Card Colors */
.card-total { border-color: #0077b6; }
.card-pending { border-color: #ffc107; }
.card-picked { border-color: #6c757d; }
.card-transit { border-color: #17a2b8; }
.card-out { border-color: #6f42c1; }
.card-delivered { border-color: #28a745; }

/* Table Styling */
.recent-orders {
  margin: 2rem 5%;
  background: #fff;
  padding: 1.5rem;
  border-radius: 12px;
  box-shadow: 0 4px 12px rgba(0,0,0,0.08);
  overflow-x: auto;
}

.recent-orders h3 { margin-top: 0; color: #0077b6; }

table { width: 100%; border-collapse: collapse; min-width: 900px; }
th, td { padding: 12px 15px; border-bottom: 1px solid #eee; font-size: 0.9rem; text-align: left; }
th { background: #f8f9fa; color: #555; font-weight: 600; text-transform: uppercase; font-size: 0.8rem; }
tr:hover { background-color: #f9f9f9; }

/* Status Badges */
.status-badge { padding: 5px 10px; border-radius: 20px; font-size: 0.75rem; font-weight: bold; text-transform: uppercase; white-space: nowrap; }

/* Status Colors (Matches CSS classes generated by PHP) */
.status-Pending { background:#fff3cd; color:#856404; }
.status-Picked-Up { background:#e2e3e5; color:#383d41; }
.status-In-Transit { background:#cce5ff; color:#004085; }
.status-Out-for-Delivery { background:#e2d9f3; color:#6f42c1; }
.status-Delivered { background:#d4edda; color:#155724; }
</style>

<div class="greeting" style="margin:2rem 5%;">
  <h2 style="color: #333;">Dashboard Overview</h2>
  <p style="color: #666;">Welcome back, <strong><?php echo htmlspecialchars($user_name); ?></strong> 👋</p>
</div>

<div class="dashboard">
  <div class="card card-total">
    <h2><?php echo $totalOrders; ?></h2>
    <p>Total Orders</p>
  </div>
  <div class="card card-pending">
    <h2><?php echo $pending; ?></h2>
    <p>Pending</p>
  </div>
  <div class="card card-picked">
    <h2><?php echo $pickedUp; ?></h2>
    <p>Picked Up</p>
  </div>
  <div class="card card-transit">
    <h2><?php echo $inTransit; ?></h2>
    <p>In Transit</p>
  </div>
  <div class="card card-out">
    <h2><?php echo $outDelivery; ?></h2>
    <p>Out for Delivery</p>
  </div>
  <div class="card card-delivered">
    <h2><?php echo $delivered; ?></h2>
    <p>Delivered</p>
  </div>
</div>

<div class="recent-orders">
  <h3>Recent Activity</h3>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Sender</th>
        <th>Receiver</th>
        <th>Status</th>
        <th>Tracking ID</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
    <?php if($recentOrders): ?>
      <?php foreach($recentOrders as $order): 
          // Replace spaces with dashes for CSS class (e.g., "Picked Up" -> "Picked-Up")
          $statusClass = str_replace(' ', '-', $order['status']);
      ?>
        <tr>
          <td><?php echo $order['id']; ?></td>
          
          <td>
            <strong><?php echo htmlspecialchars($order['sender_name']); ?></strong><br>
            <small>📞 <?php echo $order['sender_phone']; ?></small>
          </td>

          <td>
            <strong><?php echo htmlspecialchars($order['receiver_name']); ?></strong><br>
            <small>📞 <?php echo $order['receiver_phone']; ?></small>
          </td>

          <td>
            <span class="status-badge status-<?php echo $statusClass; ?>">
              <?php echo $order['status']; ?>
            </span>
          </td>

          <td style="font-family:monospace; color:#0077b6;">
            <?php echo $order['tracking_id']; ?>
          </td>
          
          <td><?php echo date('M d, Y', strtotime($order['created_at'])); ?></td>
        </tr>
      <?php endforeach; ?>
    <?php else: ?>
      <tr>
        <td colspan="6" style="text-align:center; padding: 20px; color: #999;">No orders found.</td>
      </tr>
    <?php endif; ?>
    </tbody>
  </table>
</div>

<?php include '../includes/footer.php'; ?>